/* Landing UI kit — shared inline style objects */
const landingStyles = {
  hero: {
    minHeight: '80vh',
    display: 'flex',
    alignItems: 'center',
    padding: '120px 20px 80px',
    position: 'relative',
  },
  heroContent: { maxWidth: 820, marginLeft: '5%', position: 'relative', zIndex: 2 },
  heroBadge: {
    display: 'inline-block',
    background: 'rgba(122,158,138,0.3)',
    border: '1px solid rgba(122,158,138,0.5)',
    color: '#C6F7A6',
    padding: '8px 20px',
    borderRadius: 10,
    fontFamily: 'Montserrat, sans-serif',
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: 2,
    marginBottom: 28,
  },
  h1: {
    fontFamily: 'Poppins, sans-serif',
    fontSize: 52,
    fontWeight: 700,
    lineHeight: 1.15,
    color: '#F4EDE4',
    margin: '0 0 22px',
    letterSpacing: 0,
    textTransform: 'none',
  },
  h1Sub: {
    display: 'block',
    color: 'rgba(244,237,228,0.8)',
    fontWeight: 300,
    fontSize: 22,
    letterSpacing: 0.5,
    marginTop: 14,
    fontFamily: 'Poppins, sans-serif',
  },
  heroText: {
    fontFamily: 'Poppins, sans-serif',
    fontSize: 17,
    fontWeight: 300,
    color: 'rgba(244,237,228,0.92)',
    maxWidth: 680,
    lineHeight: 1.6,
    marginBottom: 32,
  },
  ctaRow: { display: 'flex', gap: 14, flexWrap: 'wrap', marginBottom: 10 },
  cta: {
    display: 'inline-block',
    padding: '16px 32px',
    borderRadius: 8,
    fontFamily: 'Montserrat, sans-serif',
    fontWeight: 700,
    fontSize: 14,
    letterSpacing: 1,
    textTransform: 'uppercase',
    textDecoration: 'none',
    transition: 'all 0.3s ease',
  },
  ctaBordeaux: {
    background: 'linear-gradient(135deg,#6B3E44,#8B3E44)',
    color: '#fff',
    boxShadow: '0 4px 18px rgba(107,62,68,0.3)',
  },
  ctaGhost: {
    background: 'rgba(244,237,228,0.06)',
    border: '1px solid rgba(244,237,228,0.3)',
    color: '#F4EDE4',
  },
  subtext: { fontSize: 13, color: 'rgba(255,255,255,0.6)', marginTop: 8 },

  section: { maxWidth: 1100, margin: '0 auto', padding: '60px 20px' },
  sectionIntro: { textAlign: 'center', maxWidth: 680, margin: '0 auto 40px' },
  h2: {
    fontFamily: 'Poppins, sans-serif',
    fontWeight: 600,
    fontSize: 32,
    color: '#F4EDE4',
    marginBottom: 14,
    letterSpacing: 0,
    textTransform: 'none',
    border: 'none',
    padding: 0,
  },
  muted: { color: 'rgba(244,237,228,0.75)', fontSize: 16, fontFamily: 'Poppins, sans-serif', fontWeight: 300 },

  cardsGrid: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 22, perspective: 1200 },
  flipWrap: { height: 380, cursor: 'pointer' },
  flipInner: { position: 'relative', width: '100%', height: '100%', transition: 'transform 0.7s cubic-bezier(0.4,0,0.2,1)', transformStyle: 'preserve-3d' },
  flipFace: { position: 'absolute', inset: 0, WebkitBackfaceVisibility: 'hidden', backfaceVisibility: 'hidden', borderRadius: 12, overflow: 'hidden', boxShadow: '0 8px 30px rgba(0,0,0,0.25)' },
  flipFront: { background: 'rgba(15,20,45,0.45)', backdropFilter: 'blur(18px)', display: 'flex', flexDirection: 'column' },
  flipImg: { width: '100%', height: 260, objectFit: 'cover' },
  flipLabel: { padding: '18px 20px', textAlign: 'center', color: '#F4EDE4', flex: 1 },
  flipH3: { fontFamily: 'Poppins, sans-serif', fontSize: 19, fontWeight: 600, margin: 0, color: '#F4EDE4' },
  flipKeyword: { display: 'inline-block', fontSize: 11, fontWeight: 700, letterSpacing: 1, color: '#F4EDE4', background: 'rgba(244,237,228,0.1)', padding: '3px 10px', borderRadius: 4, marginTop: 8 },
  flipHint: { fontSize: 11, color: '#C4836E', marginTop: 10, letterSpacing: 0.3, fontWeight: 600 },
  flipBack: { transform: 'rotateY(180deg)', padding: '30px 26px', display: 'flex', alignItems: 'center', color: '#F4EDE4' },
  flipBackText: { fontFamily: 'Poppins, sans-serif', fontWeight: 300, fontSize: 15, lineHeight: 1.7, margin: 0 },

  glassBox: {
    background: 'rgba(15,20,45,0.45)',
    backdropFilter: 'blur(18px)',
    WebkitBackdropFilter: 'blur(18px)',
    border: '1px solid rgba(122,158,200,0.18)',
    borderRadius: 14,
    boxShadow: '0 10px 50px rgba(0,0,0,0.4)',
    padding: 48,
    maxWidth: 760,
    margin: '0 auto',
  },
  eyebrow: {
    display: 'inline-block',
    fontFamily: 'Montserrat, sans-serif',
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 3,
    textTransform: 'uppercase',
    color: '#7A9E8A',
    marginBottom: 18,
  },
};
window.landingStyles = landingStyles;
