/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WillkommenRouteImport } from './routes/willkommen'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as GlossarRouteImport } from './routes/glossar'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulSlugRouteImport } from './routes/modul.$slug'

const WillkommenRoute = WillkommenRouteImport.update({
  id: '/willkommen',
  path: '/willkommen',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarRoute = GlossarRouteImport.update({
  id: '/glossar',
  path: '/glossar',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulSlugRoute = ModulSlugRouteImport.update({
  id: '/modul/$slug',
  path: '/modul/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/datenschutz': typeof DatenschutzRoute
  '/einstellungen': typeof EinstellungenRoute
  '/glossar': typeof GlossarRoute
  '/journal': typeof JournalRoute
  '/onboarding': typeof OnboardingRoute
  '/willkommen': typeof WillkommenRoute
  '/modul/$slug': typeof ModulSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/datenschutz': typeof DatenschutzRoute
  '/einstellungen': typeof EinstellungenRoute
  '/glossar': typeof GlossarRoute
  '/journal': typeof JournalRoute
  '/onboarding': typeof OnboardingRoute
  '/willkommen': typeof WillkommenRoute
  '/modul/$slug': typeof ModulSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/datenschutz': typeof DatenschutzRoute
  '/einstellungen': typeof EinstellungenRoute
  '/glossar': typeof GlossarRoute
  '/journal': typeof JournalRoute
  '/onboarding': typeof OnboardingRoute
  '/willkommen': typeof WillkommenRoute
  '/modul/$slug': typeof ModulSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/datenschutz'
    | '/einstellungen'
    | '/glossar'
    | '/journal'
    | '/onboarding'
    | '/willkommen'
    | '/modul/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/datenschutz'
    | '/einstellungen'
    | '/glossar'
    | '/journal'
    | '/onboarding'
    | '/willkommen'
    | '/modul/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/datenschutz'
    | '/einstellungen'
    | '/glossar'
    | '/journal'
    | '/onboarding'
    | '/willkommen'
    | '/modul/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DatenschutzRoute: typeof DatenschutzRoute
  EinstellungenRoute: typeof EinstellungenRoute
  GlossarRoute: typeof GlossarRoute
  JournalRoute: typeof JournalRoute
  OnboardingRoute: typeof OnboardingRoute
  WillkommenRoute: typeof WillkommenRoute
  ModulSlugRoute: typeof ModulSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/willkommen': {
      id: '/willkommen'
      path: '/willkommen'
      fullPath: '/willkommen'
      preLoaderRoute: typeof WillkommenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossar': {
      id: '/glossar'
      path: '/glossar'
      fullPath: '/glossar'
      preLoaderRoute: typeof GlossarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modul/$slug': {
      id: '/modul/$slug'
      path: '/modul/$slug'
      fullPath: '/modul/$slug'
      preLoaderRoute: typeof ModulSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DatenschutzRoute: DatenschutzRoute,
  EinstellungenRoute: EinstellungenRoute,
  GlossarRoute: GlossarRoute,
  JournalRoute: JournalRoute,
  OnboardingRoute: OnboardingRoute,
  WillkommenRoute: WillkommenRoute,
  ModulSlugRoute: ModulSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
